### ISSUE TITLE
BEEGO_CONFIG_PATH  是什么内容?

### ISSUE THREAD

**Issue by whzywxt** [gobbscom/go-bbs#2]

**Comment by 1920853199** [comment]
```
创建一个配置文件，app.conf 内容如 app.conf.example，配置好环境变量 BEEGO_CONFIG_PATH = '配置文件路径'
```

**Comment by zhoushiya** [comment]
> ```
> 创建一个配置文件，app.conf 内容如 app.conf.example，配置好环境变量 BEEGO_CONFIG_PATH = '配置文件路径'
> ```

不好意思，go新手，请问这个环境变量是在哪里配置？

**Comment by 1920853199** [comment]
> > ```
> > 创建一个配置文件，app.conf 内容如 app.conf.example，配置好环境变量 BEEGO_CONFIG_PATH = '配置文件路径'
> > ```
> 
> 不好意思，go新手，请问这个环境变量是在哪里配置？

环境变量就是系统的环境变量的意思，如果不是很清楚的话，可以查一下系统环境变量怎么设置，不同的系统下面有不同的设置方法呢。

当然你也可以在项目的根目录下创建一个一个目录conf，然后把 app.conf文件放进去。

**Comment by zhoushiya** [comment]
> > > ```
> > > 创建一个配置文件，app.conf 内容如 app.conf.example，配置好环境变量 BEEGO_CONFIG_PATH = '配置文件路径'
> > > ```
> > 
> > 
> > 不好意思，go新手，请问这个环境变量是在哪里配置？
> 
> 环境变量就是系统的环境变量的意思，如果不是很清楚的话，可以查一下系统环境变量怎么设置，不同的系统下面有不同的设置方法呢。
> 
> 当然你也可以在项目的根目录下创建一个一个目录conf，然后把 app.conf文件放进去。

非常感谢，程序很不错，功能很多，我再尝试下
